FROM python:2.7.18-buster AS inspire-schemas-py2-tests

ARG APP_HOME=/code
WORKDIR ${APP_HOME}

COPY . .

RUN python -m pip install --user --upgrade pip
RUN python -m pip --no-cache-dir install --user -e .[tests,docs]

CMD ["/bin/bash"]
