name: Test Python 3

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Lint - Pre-commit check
        uses: pre-commit/action@v3.0.1
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install npm dependencies
        run: |
          npm install buffer-shims
          npm install --global rollup

      - name: Install python dependencies
        run: |
          python -m pip  install --user --upgrade pip
          pip --no-cache-dir install --user -e .[tests,docs]

      - name: Show python dependencies
        run: |
          python --version
          pip freeze

      - name: Run tests
        run: |
          ./run-tests.sh
