name: Test Python 3

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.11', '3.12', '3.13', '3.14']
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python }}

      - name: Install python dependencies
        run: |
          pipx install poetry==2.2.1
          poetry install --with test,docs --no-interaction

      - name: Show python dependencies
        run: |
          python --version
          poetry show

      - name: Build Test
        run: |
          poetry run ./tests/integration/test_setup.sh

      - name: Run tests
        run: |
          poetry run pytest
